# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: fmgs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=11.8
  - plyfile=0.8.1
  - pip=22.3.1
  - pytorch=2.0.1
  - torchaudio=2.0.2
  - torchvision=0.15.2
  - tqdm
  - scikit-learn
  - matplotlib
  - opencv
  - pip:
      - third_party/diff-gaussian-rasterization
      - third_party/simple-knn
      - third_party/simple-diff-gaussian-rasterization
      - jaxtyping
      - open_clip_torch
      - timm
      - ftfy
      - regex
      - clip @ git+https://github.com/openai/CLIP.git
      - git+https://github.com/facebookresearch/segment-anything.git
      - git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
